Vagrant.configure("2") do |config|

  # Supports local cache, don't waste bandwitdh
  # vagrant plugin install vagrant-cachier
  # https://github.com/fgrehm/vagrant-cachier 
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.auto_detect = true
  end

  # Box configuration
  config.vm.box = "ubuntu/trusty64"
  config.vm.network :private_network, ip: "10.9.8.10"

  config.vm.provider "virtualbox" do |v|
    # On VirtualBox, we don't have guest additions or a functional vboxsf
    # in TinyCore Linux, so tell Vagrant that so it can be smarter.
    v.check_guest_additions = false
    v.functional_vboxsf     = false
    v.memory = 1024
  end

  # Provisioning stuff. Provisioning using 'docker' provisioner, but no
  # args, installs and configures the latest version of Docker. 
  config.vm.provision "docker"
  config.vm.provision "shell", inline: "ps aux | grep 'sshd:' | awk '{print $2}' | xargs kill"
end
